name: CI/CD Pipeline through Github Action Runner

on:
  push:
    branches:
      - main

jobs:
  # lint:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Lint
  #       run: npm run lint

  build-deploy:
    # needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: pm2 restart all || pm2 start npm --name "motherbox" -- start
