name: CI/CD for HubNode-Box

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # Using Node.js version 18

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
      env:
        CI: true

    - name: Build
      run: |
        echo "Building the Next.js application..."
        npm run build

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} -r .next/* ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd ${{ secrets.TARGET_DIR }} && npm install --production && pm2 restart all"
      env:
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
