name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install

  lint:
    needs: setup
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: npm run lint

  build:
    needs: lint
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Start/Restart Application
      run: pm2 restart all || pm2 start npm --name "next-app" -- start
